project:
  type: website
  preview:
    browser: false

website:
  title: "test-evaluate-code-3"
  site-url: "https://tylere.github.io/test-evaluate-code-3"
  description: "Test out evaluating code in nbdev notebooks."
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/tylere/test-evaluate-code-3"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/tylere/test-evaluate-code-3"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
